const url = "http://192.168.0.29:7001" //"http://www.huishenghuo.net:7001"
exports.accountUrl = url + "/account"
exports.loginUrl = url + "/servicer/login"
exports.serviceListUrl = url + "/serviceList"
exports.cacheUrl = url + "/mpCache"
exports.serviceUrl = url + "/service"
exports.fileUploadUrl = url + "/service/file"
exports.fileUploadPageUrl = url + "/service/file/page"
const SERVICER_URL = url + "/servicer"
exports.LOGIN_URL = SERVICER_URL + "/login"
//"http://192.168.0.29:7001/static/miniprogram"
exports.chatUrl = "http://www.huishenghuo.net:3000" //"http://192.168.0.29:3000"