const url = "http://www.huishenghuo.net:7001"
exports.accountUrl = url + "/account"
exports.loginUrl = url + "/servicer/login"
exports.serviceListUrl=url+"/serviceList"
exports.cacheUrl = url + "/mpCache"
exports.serviceUrl = url + "/service" 
exports.fileUploadUrl = url + "/service/file"
exports.fileUploadPageUrl = url + "/service/file/page"
exports.DOWNLOAD_PAGE_URL=url+"/download_page"
//"http://192.168.0.29:7001/static/miniprogram"
exports.chatUrl = "http://www.huishenghuo.net:3000"//"http://192.168.0.29:3000"